---
- name: Check Python Version
  hosts: all
  gather_facts: no
  tasks:
    - name: Run Python version command
      ansible.builtin.command: python3 --version
      register: python_version
      ignore_errors: yes  # Prevents playbook failure if Python is not found

    - name: Debug full command output
      ansible.builtin.debug:
        var: python_version

    - name: Display Python version
      ansible.builtin.debug:
        msg: "Python version: {{ python_version.stdout | default('Command failed or Python not found') }}"
